FROM python:3.12-slim AS linux-base

ARG TARGETARCH

# Utilities
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends build-essential \
    sudo curl git htop less rsync screen vim nano wget ca-certificates openssh-client zsh procps psmisc \
    iptables ipset iproute2 dnsutils aggregate jq gfortran pkg-config

# Download and install VS Code Server CLI
RUN ARCH="$TARGETARCH" && [ "$ARCH" = "amd64" ] && ARCH="x64"; \
    wget -O /tmp/vscode-server-cli.tar.gz "https://update.code.visualstudio.com/latest/cli-linux-${ARCH}/stable" && \
    mkdir -p /usr/local/bin && \
    tar -xf /tmp/vscode-server-cli.tar.gz -C /usr/local/bin && \
    rm /tmp/vscode-server-cli.tar.gz

# Non-root user
RUN useradd -m -s /bin/bash devuser

FROM linux-base AS python-base

WORKDIR /srv/repo

# Environment variables
ENV UV_PROJECT_ENVIRONMENT="/venv"
ENV UV_PYTHON_INSTALL_DIR="/python"
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_PYTHON=python3.12
ENV PATH="$UV_PROJECT_ENVIRONMENT/bin:$PATH"
ENV PYTHONPATH="/srv/repo/src:$PYTHONPATH"
# See https://github.com/jax-ml/jax/issues/29260
ENV LD_LIBRARY_PATH="/venv/lib/python3.12/site-packages/nvidia/cuda_nvrtc/lib:$LD_LIBRARY_PATH"

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.6.6 /uv /usr/local/bin/uv
RUN mkdir -p /venv && chown devuser:devuser /venv

USER devuser

RUN --mount=type=cache,target=/home/devuser/.cache/uv,uid=1000 \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --all-groups --extra cuda
